/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "../../lvgl/src/lv_conf_internal.h"
#include "src/emulation/test_emu.h"
#include "lvgl.h"
#include "lvgl/src/others/test/lv_test_display.h"
#include "lvgl/src/misc/lv_timer.h"
#include "lvgl/src/others/test/lv_test_indev.h"
#include "lvgl/src/others/test/lv_test_screenshot_compare.h"
#include "lvgl/src/others/test/lv_test_helpers.h"
#include <time.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_btns_created(void);
extern void test_btns_named(void);
extern void test_btns_events(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_main.c");
  run_test(test_btns_created, "test_btns_created", 96);
  run_test(test_btns_named, "test_btns_named", 114);
  run_test(test_btns_events, "test_btns_events", 128);

  return UnityEnd();
}
